"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ShieldCheck, Smartphone, Lock, ArrowLeft, Copy } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { clearSession } from "@/lib/auth";

type Step = "loading" | "enroll" | "verify";

interface Enrollment {
  factorId: string;
  qrCode: string;
  secret: string;
}

export default function MFAPage() {
  const router = useRouter();
  const [step, setStep] = useState<Step>("loading");
  const [factorId, setFactorId] = useState("");
  const [enrollment, setEnrollment] = useState<Enrollment | null>(null);
  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [role, setRole] = useState<string>("");

  useEffect(() => {
    (async () => {
      const {
        data: { user },
      } = await supabase.auth.getUser();
      if (!user) {
        router.replace("/login");
        return;
      }
      setRole((user.app_metadata?.app_role as string) ?? "");

      const { data: factors } = await supabase.auth.mfa.listFactors();
      const verified = factors?.totp.find((f) => f.status === "verified");
      if (verified) {
        setFactorId(verified.id);
        setStep("verify");
        return;
      }

      // Drop half-finished enrolments so enroll() doesn't hit the factor limit.
      for (const f of factors?.all ?? []) {
        if (f.status === "unverified") {
          await supabase.auth.mfa.unenroll({ factorId: f.id });
        }
      }
      const { data, error } = await supabase.auth.mfa.enroll({
        factorType: "totp",
        friendlyName: `MediSecure ${new Date().toISOString().slice(0, 10)}`,
      });
      if (error || !data) {
        setError(error?.message ?? "Could not start enrolment");
        setStep("enroll");
        return;
      }
      setEnrollment({ factorId: data.id, qrCode: data.totp.qr_code, secret: data.totp.secret });
      setFactorId(data.id);
      setStep("enroll");
    })();
  }, [router]);

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (code.length !== 6) return;
    setBusy(true);
    setError("");
    const { error } = await supabase.auth.mfa.challengeAndVerify({ factorId, code });
    setBusy(false);
    if (error) {
      setCode("");
      setError("That code didn't match. Codes change every 30 seconds; try the current one.");
      return;
    }
    // The session is now aal2; RLS will release clinical data.
    router.replace(role ? `/dashboard/${role}` : "/login");
  };

  const cancel = async () => {
    await clearSession();
    router.replace("/login");
  };

  return (
    <div className="min-h-screen bg-[conic-gradient(at_top,_var(--tw-gradient-stops))] from-blue-50 via-indigo-50 to-slate-50 dark:from-slate-950 dark:via-blue-950 dark:to-indigo-950 flex items-center justify-center p-4">
      <div className="w-full max-w-md p-8 backdrop-blur-xl bg-white/70 dark:bg-gray-900/70 border border-white/50 dark:border-white/10 rounded-3xl shadow-2xl dark:shadow-black/40 space-y-6">
        <button
          onClick={cancel}
          className="inline-flex items-center text-blue-600 hover:text-blue-800 dark:text-blue-400 text-sm font-medium"
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Sign out
        </button>

        <div className="flex items-start gap-3">
          <div className="p-2 rounded-xl bg-blue-100 dark:bg-blue-900/50">
            <ShieldCheck className="w-6 h-6 text-blue-700 dark:text-blue-300" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-gray-800 dark:text-gray-100">
              {step === "enroll" ? "Set up two-factor authentication" : "Two-factor authentication"}
            </h1>
            <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
              {step === "enroll"
                ? "Clinical records stay locked until this session is verified with an authenticator app."
                : "Enter the 6-digit code from your authenticator app."}
            </p>
          </div>
        </div>

        {step === "loading" && (
          <p className="text-sm text-gray-500 animate-pulse">Checking your security settings…</p>
        )}

        {step === "enroll" && enrollment && (
          <div className="space-y-4">
            <ol className="text-sm text-gray-700 dark:text-gray-300 space-y-1 list-decimal list-inside">
              <li>Open Google Authenticator, 1Password, Authy or similar.</li>
              <li>Scan this code, or enter the key manually.</li>
              <li>Type the 6-digit code it shows.</li>
            </ol>
            <div className="flex justify-center">
              {/* qr_code is an SVG data URL generated by Supabase Auth */}
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={enrollment.qrCode}
                alt="QR code for your authenticator app"
                className="w-48 h-48 bg-white p-2 rounded-xl border border-gray-200"
              />
            </div>
            <button
              type="button"
              onClick={() => navigator.clipboard?.writeText(enrollment.secret)}
              className="w-full flex items-center justify-between gap-2 px-3 py-2 rounded-lg bg-gray-100 dark:bg-gray-800 text-xs font-mono text-gray-700 dark:text-gray-300 break-all text-left"
              title="Copy setup key"
            >
              <span>{enrollment.secret}</span>
              <Copy className="w-4 h-4 shrink-0" />
            </button>
          </div>
        )}

        {step !== "loading" && (
          <form onSubmit={submit} className="space-y-4">
            {error && (
              <div className="p-3 rounded-lg border-l-4 border-red-500 bg-red-50 dark:bg-red-950/40">
                <p className="text-sm font-medium text-red-700 dark:text-red-300">{error}</p>
              </div>
            )}
            <div>
              <label htmlFor="totp" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Authenticator code
              </label>
              <div className="relative">
                {step === "enroll" ? (
                  <Smartphone className="absolute left-3 top-3.5 w-5 h-5 text-gray-400" />
                ) : (
                  <Lock className="absolute left-3 top-3.5 w-5 h-5 text-gray-400" />
                )}
                <input
                  id="totp"
                  inputMode="numeric"
                  autoComplete="one-time-code"
                  value={code}
                  onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 6))}
                  placeholder="000000"
                  autoFocus
                  disabled={busy}
                  className="w-full pl-10 pr-4 py-3 text-center text-2xl font-bold tracking-widest border-2 border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100 rounded-lg focus:outline-none focus:border-blue-500"
                />
              </div>
            </div>
            <button
              type="submit"
              disabled={busy || code.length !== 6}
              className="w-full py-3 rounded-lg bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white font-semibold"
            >
              {busy ? "Verifying…" : step === "enroll" ? "Verify and turn on" : "Verify"}
            </button>
          </form>
        )}
      </div>
    </div>
  );
}
