import { supabase } from "./supabase";

interface LogActionParams {
  userId: string;
  userRole: "admin" | "patient" | "doctor" | "nurse" | "staff";
  action: string;
  resourceType?: string;
  resourceId?: string;
  ipAddress?: string;
  userAgent?: string;
}

export async function logAction(params: LogActionParams): Promise<void> {
  try {
    const {
      userId,
      userRole,
      action,
      resourceType,
      resourceId,
      ipAddress,
      userAgent,
    } = params;

    const { error } = await supabase.from("access_logs").insert({
      user_id: userId,
      user_role: userRole,
      action,
      resource_type: resourceType ?? null,
      resource_id: resourceId ?? null,
      ip_address: ipAddress ?? null,
      user_agent: userAgent ?? null,
      // timestamp is auto-generated by DB
    });

    if (error) {
      console.error("DB audit log failed:", error);
      return;
    }

    // ✅ Blockchain logging (server-only, non-blocking)
    if (typeof window === "undefined") {
      try {
        const { logToBlockchain } = await import(
          "@/lib/blockchain/blockchainLogger"
        );

        await logToBlockchain("AUDIT_LOG", {
          userId,
          userRole,
          action,
          resourceType,
          resourceId,
          timestamp: new Date().toISOString(),
        });
      } catch (blockchainError) {
        console.error("Blockchain audit log failed:", blockchainError);
      }
    }
    
  } catch (err) {
    console.error("Audit logging crashed:", err);
  }

}

export async function getAllLogs(limit: number = 100) {
  try {
    const { data, error } = await supabase
      .from("access_logs")
      .select("*")
      .order("timestamp", { ascending: false })
      .limit(limit);

    if (error) {
      console.error("Failed to fetch logs:", error);
      return [];
    }

    return data || [];
  } catch (error) {
    console.error("Failed to fetch logs:", error);
    return [];
  }
}

export async function getLogsByUser(userId: string, limit: number = 50) {
  try {
    const { data, error } = await supabase
      .from("access_logs")
      .select("*")
      .eq("user_id", userId)
      .order("timestamp", { ascending: false })
      .limit(limit);

    if (error) {
      console.error("Failed to fetch user logs:", error);
      return [];
    }

    return data || [];
  } catch (error) {
    console.error("Failed to fetch user logs:", error);
    return [];
  }
}

export async function getLogsByRole(userRole: string, limit: number = 50) {
  try {
    const { data, error } = await supabase
      .from("access_logs")
      .select("*")
      .eq("user_role", userRole)
      .order("timestamp", { ascending: false })
      .limit(limit);

    if (error) {
      console.error("Failed to fetch role logs:", error);
      return [];
    }

    return data || [];
  } catch (error) {
    console.error("Failed to fetch role logs:", error);
    return [];
  }
}
